[package]
name = "network"
version = "0.1.0"
edition = "2021"

[dependencies]
node = { path = "../node"}

serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "macros", "net"] }
tower = "0.4.13"
tower-http = "0.5.2"
