[package]
name = "ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

hex = { workspace = true }
sha2 = { workspace = true }
ecdsa = { workspace = true }
k256 = { workspace = true }
serde = { workspace = true }
