[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]

hex = { workspace = true }
sha2 = { workspace = true }
ecdsa = { workspace = true }
pem = { workspace = true }
base64 = { workspace = true }
k256 = { workspace = true }
rand_core = { workspace = true }
